#pragma once
#include <stdint.h>

#define PRIMARY_ATA_BUS_IO_BASE 0x1F0
#define PRIMARY_ATA_BUS_CONTROL_BASE 0x3F6

#define SECONDARY_ATA_BUS_IO_BASE 0x170
#define SECONDARY_ATA_BUS_CONTROL_BASE 0x376

#define ATA_IO_DATA_REGISTER 0
#define ATA_IO_ERROR_REGISTER 1
#define ATA_IO_FEATURES_REGISTER 1
#define ATA_IO_SECTOR_COUNT_REGISTER 2
#define ATA_IO_SECTOR_NUMBER_REGISTER 3
#define ATA_IO_LCYL_REGISTER 4
#define ATA_IO_HCYL_REGISTER 5
#define ATA_IO_DRIVE_REGISTER 6
#define ATA_IO_STATUS_REGISTER 7
#define ATA_IO_COMMAND_REGISTER 7

#define ATA_CONTROL_STATUS_REGISTER 0
#define ATA_CONTROL_DEVICE_REGISTER 0
#define ATA_CONTROL_DRIVE_REGISTER 1

#define ATA_ENABLE_INTERRUTPS 0x0
#define ATA_DISABLE_INTERRUTPS 0x2

#define ATA_PRIMARY_IRQ 14
#define ATA_SECONDARY_IRQ 15

#define ATA_STATUS_ERR (1 << 0)
#define ATA_STATUS_IDX (1 << 1)
#define ATA_STATUS_CORR (1 << 2)
#define ATA_STATUS_DRQ (1 << 3)
#define ATA_STATUS_SRV (1 << 4)
#define ATA_STATUS_DF (1 << 5)
#define ATA_STATUS_RDY (1 << 6)
#define ATA_STATUS_BSY (1 << 7)

#define ATA_SECTOR_SIZE 512

#define ATA_IDENTIFY_DATA_SIZE 512
#define ATA_IDENTIFY_DATA_SECTOR_NUMBER_OFFSET 114
#define ATA_IDENTIFY_DATA_MODEL_STRING_OFFSET 54
#define ATA_IDENTIFY_DATA_MODEL_STRING_SIZE 40
#define ATA_IDENTIFY_DATA_SERIAL_STRING_OFFSET 20
#define ATA_IDENTIFY_DATA_SERIAL_STRING_SIZE 20
#define ATA_IDENTIFY_DATA_FIRMWARE_STRING_OFFSET 46
#define ATA_IDENTIFY_DATA_FIRMWARE_STRING_SIZE 8